name: build-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - opened
    
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: downloading-dependencies
        run: npm ci
      - name: test
        run:  | 
          npm test
          echo "test completed successfully"
  build: 
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: downloading-dependencies
        run: npm ci
      - name: build
        run: |
          npm run build
          echo "build completed successfully"