name: build-test
on:
  push:
    branches:
      - master
      - 'release/**'
      - 'hotfix/**'
      - 'testing-*'
    paths-ignore:
      - '.github/**'
    
      
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - dev
      - test
##
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: caching downloading-dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      - name: downloading-dependencies
        run: npm ci
      - name: test
        run:  | 
          npm test
          echo "test completed successfully"
  build: 
    needs: test 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: caching downloading-dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: downloading-dependencies
        run: npm ci
      - name: build
        run: |
          npm run build
          echo "build completed successfully"
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact 
          path: ./dist
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: deploy
        run: |
          ls -la
          echo " deploy completed successfully"
      